name: Ruff

on:
    pull_request:
        paths:
            - "src/**"
            - "tests/**"

concurrency:
    group: ${{ github.ref }}-${{ github.head_ref }}-ruff
    cancel-in-progress: true

jobs:
    ruff:
        name: Ruff
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: astral-sh/ruff-action@v3
            -   name: Ruff format
                run: ruff format --check
            -   name: Ruff check
                run: ruff check --output-format=github .
